### PR TITLE
Add phpdoc for better IDE support

### PR DESCRIPTION
**Pull request by liayn**

### CODE REVIEW

**Comment by marcoceppi** [comment]
I'll comb through this, but I'm a :+1: to better documentation

**Comment by liayn** [comment]
This one got really huge. I mainly added typehints everywhere and fixed stuff like undeclared class properties.

**Comment by liayn** [comment]
My PHPStorm now has not much to complain about anymore. ;-)

**Comment by liayn** [comment]
Thanks very much for this speed merge.

**Pull request merged**
